### PR TITLE
Shading and autocheck revamp

### PR DESCRIPTION
**Pull request by robx**
This PR is an attempt to improve the autocheck situation with shading puzzles, particularly to get more consistency.

The main parts:

- switch cave and nurimisaki back to primarily a shading rather than unshading puzzle (that was done at the time to deal with the irritating autocheck behavior
- enable heyawake-style autocheck guards for some shading puzzles which suffer from surprise autocheck
- allow naive autocheck behaviour with an option (but default to guarded autocheck)

Todo:
- [x] rework unshaded-cell styling for cave (currently dots which don't work well with clues)
- [x] rework unshaded-cell styling for nurimisaki (currently green bg, but I think dots are nicer with immediately-decided clue cells
- [x] go over puzzles with `numberRemainsUnshaded`; might be worth using dots for nurimaze as well

~~This is also to explore whether / how to improve the autocheck guards. In particular, as of the time of writing:~~

- ~~heyawake treats next-to-shaded-cells as decided, so you only need to mark a few cells empty to trigger autocheck~~
- ~~to aid this change visually, switch to stostone style large dots to mark unshaded cells~~
- ~~creek considers next-to-clue cells as decided~~

~~To do (at least as things to try):~~
- ~~treat cells in clued rooms as decided (e.g. it shouldn't be necessary to mark 0-clued rooms empty)~~
- ~~treat cells in view of a clue as decided in cave, kurodoko, nurimisaki~~

### CODE REVIEW

**Comment by robx** [comment]
Current state is live here: https://garp.vllmrt.net/scratch/autocheck/list.html

**Comment by robx** [comment]
Some other types that should be touched here:

- nurimaze

**Comment by x-sheep** [comment]
I have to say that I _really_ dislike the current answer checker in Heyawake, to the point where I actively avoid playing Heyawake puzzles on [puzz.link](https://puzz.link/) and use [pzv.jp](http://pzv.jp/) every single time. What bothers me specifically is the feeling that the validity of an answer changes under observation. When the change was first rolled out, I (along with multiple Twitter users) mistook it for a bug.

I suggest implementing an option similar to Fillomino's "Force every cell to have a number", where uncertain cells are presented as errors. This would prevent the Completed window from appearing at unexpected moments, not just during gameplay, but also when actively pressing the Check button. Disabling the option means that auxiliary marks are not required for a valid solution.

This doesn't actually negate this PR, but I really hope this problem is addressed before this type of answer validation is expanded to other types.

**Comment by robx** [comment]
I'm happy to consider treating uncertain cells as proper errors, but would not want to make this optional.

For Heyawake specifically, this could be combined with the implementation in this PR of treating shaded-adjacent cells as unshaded via an autocmp-feature which displays them immediately as unshaded to require effectively the same amount of shading/unshading as presently. Or we go fully simple and just strictly require all cells to be marked by the player for these puzzles.

(I don't particularly care about whether players that are used to the pzv.jp behaviour (which I would define as buggy) are initially surprised by how puzz.link heyawake works and find it buggy. I do worry that the present implementation might be confusing and hard to figure out for new players. If I didn't  rather like the autocheck functionality where it works, I'd probably suggest dropping it entirely rather than have it work fine for some puzzle types and poorly for others.)

Also note that this fixes an issue that people seem to be similarly upset about, which is the inverted nurikabe/cave rules.

**Comment by x-sheep** [comment]
> I'm happy to consider treating uncertain cells as proper errors, but would not want to make this optional.

This works for me.

**Comment by robx** [comment]
I've switched things around a bit, going for simple current-heyawake-style autocheck guards for all shading puzzles with a connected unshaded component. And adding an option to allow disabling the guards. The smart guarding code has moved to #156.

**Comment by robx** [comment]
I'm not sure that shading first is the way to go for cave... https://garp.vllmrt.net/scratch/autocheck/p.html?cave/14/14/v3r2t4v4r2h2r4t3g3r3u3t3r3u2u

**Pull request merged**
