### PR TITLE
Add N-Back

### PR DESCRIPTION
**Pull request by cjquines**
i know of at least three triple backs: [1](https://blog.vero.site/post/puzzle-49), [2](https://mellowmelon.wordpress.com/2009/12/20/puzzle-135/), and [3](http://puzzleparasite.blogspot.com/2011/12/puzzle-80-double-back-triple-back.html). my friend nudged me to just make it fully general and PR an n-back puzzle to puzz.link. so yeah

### CODE REVIEW

**Comment by robx** [comment]
Hey! Thanks for the PR. I have a couple of doubts about this, with no sure conclusion.

- this seems less like n-back (I'd expect that to be more like a take on doubleback where the number of visits is fixed globally, like the number of stars in star battle), but rather some other "number of visits" loop
- I'm not sure how I feel about adding variants on doubleback, given that they seem pretty rare, and not even double back has been taken up particularly by authors

I feel like "number of visits" loop might exist as a type, maybe under some name?

**Comment by cjquines** [comment]
yeah, after thinking about this, i think i’ll close this PR for now—i didn’t realize that doubleback was somewhat unpopular in the first place?

**Comment by robx** [comment]
n-visits-loop has gone by Haisu Loop in some loop mashup puzzles (e.g. the LMI Meta Loop contest https://logicmastersindia.com/2020/04F/); I could see that as a potential addition.

**Comment by cjquines** [comment]
i do see the possibility of factoring some puzzles into “number of visits” or “loops with regions”. moon or sun, country road, onsen-meguri, double back, regional yajilin (? a stretch), maxi loop, detour, haisu, and n-visits-loop.

**Pull request closed without merging**
