### PR TITLE
Add Castle Wall type

### PR DESCRIPTION
**Pull request by x-sheep**
Here's another type which appeared on Puzzle Square recently. The original concept is by [Palmer Mebane](https://mellowmelon.wordpress.com/castle-wall/).

Rules:
* Draw a loop through some of the cells, so that shaded cells are outside the loop and unshaded (grey) cells are inside the loop.
* A number with an arrow indicates the number of line segments in that direction. Vertical arrows only count vertical lines, and horizontal arrows count horizontal lines.

### CODE REVIEW

**Comment by robx** [comment]
great, I was just thinking of adding it myself

**Comment by robx** [comment]
- It's a rather common variant to allow gray clue cells which can be inside or outside the loop. Thus it'd be nice to support those, and the paint the inside cells properly white. (Was there a particular reason you chose gray instead of white?)
- I'd like to have a check like Yajilin's `checkNumberHasArrow` (perhaps use that directly by moving it to `src/variety-common`?) so that puzzles with arrow-less numbers don't pretend to be valid puzzles.
- Autocomplete seems to have stale data after "Erase answer". (Could you make sure that also works with things like flipping/rotating/shrinking the board?)

**Comment by x-sheep** [comment]
I've fixed the stale autocomplete data and added `checkNumberHasArrow`.

I've never actually encountered a Castle Wall puzzle with a combination of white/gray/black cells. I only know of the Antisymmetric variant ([GMPuzzles](https://www.gmpuzzles.com/blog/2019/06/castle-wall-antisymmetry-by-ashish-kumar/) and [MellowMelon](https://mellowmelon.wordpress.com/2011/10/02/puzzle-365/)), where all cells are gray and each black clue has a white clue on the opposite end of the grid. I don't know if it's worth the effort to add this.

The only reason I used gray instead of white is because I used Yajilin as a basis for this puzzle. I slightly prefer the current look, but I'm fine with using white instead.

**Comment by robx** [comment]
The gray clues feature prominently in the Toketa books, see e.g. https://puzzle-toketa.blogspot.com/2019/09/vol_25.html

**Comment by x-sheep** [comment]
I've now added gray cells to the encoding/decoding and saved games. The editor doesn't have them yet.

**Comment by robx** [comment]
thanks, this looks good; I made some small changes to the encoding and shading input today, expect to release this soon.

**Pull request merged**
