### PR TITLE
Add Nonogram + support for multiple rows of excell

### PR DESCRIPTION
**Pull request by x-sheep**
To do:
- ~~Expanding / reducing an existing board is completely broken~~
- ~~Implement answer check~~
- Think about gaps in clue number placements. Flipping or turning a board will now leave a gap between the numbers and the board. Should these be removed? Would this cause the board to be different when doing a turn/flip and undoing it?

### CODE REVIEW

**Comment by robx** [comment]
Hey! Sorry for being so unresponsive; I should get around to going over this this weekend.

**Comment by robx** [comment]
First off, thanks for working on this! Multiple rows of excells is a sorely lacking fundamental piece of infrastructure.

I haven't looked at the diff in much detail yet, my comments so far are from playing around with the nonogram editor a bit. Mostly things seem to work nicely, this should be good to merge from a player point of view, and from an editor point of view once we've decided what to do with those gaps you mention.

My rough thoughts on that (please weigh in!):

- Logically, I'd like to think of a set of external clues for a row as a gapless list (which would be displayed flush against the board). For all the multi-external-clue puzzles I can think of, gaps don't have meaning (or they could/would be marked with some placeholders.
- Both for editing and in terms of the cell representation, it makes a whole lot of sense to treat them as a proper grid.

I think we should try to find a way to collapse the grid to a gapless list at some point. (That could just mean shifting things in the grid, no need to have an actual list representation.) I don't really see that working well while editing (e.g. after you move the cursor out of a row of excells, that row gets shifted towards the board).

So my suggestion would be to do that on encoding to URL (and, optionally, to offer a flush clues button in the editor in addition). Rotating/flipping could also flush automatically, or stay as is -- I don't think that matters so much. Saving to file could (or should even?) keep the grid representation, without flushing.

What do you think, could that work?

One other minor issue I saw is that the left margin looks weird on the Nonogram rules page. Might just be a rules page issue, but perhaps something is off with the size calculation?

**Comment by x-sheep** [comment]
Other than the puzzles on the rules page not being cropped, they look fine by me. It's probably an issue with the rules page itself, and I don't know if it's worth fixing.

Having a "Flush" button is definitely a good idea, and I'm not sure if we need to automatically flush anywhere else (considering it would probably break several undo/redo type unit tests). What would be the best position to place the button in?

**Comment by robx** [comment]
My argument for flushing automatically on encoding would be to explicitly not support gaps in shared puzzles, since those don't have meaning. (Ideally, I'm imagining the URL encoding making use of this, by explicitly encoding a list of lists of clues. How does the encoding currently determine the number of excell rows/columns?)

**Pull request merged**
