### PR TITLE
feat: add lines to nurimaze

### LINKED ISSUE #299: Feature request: line drawing on Nuri-Maze puzzles
It would be very useful to be able to draw lines on Nuri-Maze puzzles to show where the shortest path is going.

E.g. this puzzle:

https://puzz.link/p?nurimaze/31/45/nmrpbktfrlvnlldrtfnulvftfvbprvqjlelundtvvpfqvvmavvndrvtrvr4vaturqlnejfvvrntmevvvbvt6crvtmmvfpidtlqnfuqvluvnnvbaumauvfjtvmtvvqnrrfvnftftnvlnmjustvffvjstvfmudcrurtrrnrtrrftfunuvvvvvudnrmulufcvrrrirfvujtvofusvqvvtrfvjuflrdvjvvlnpfldfvunvuvlvr9psrt7nvn7rvrvbntdtttvteublarmmfdmnsf3tnnlvnbupnevantqutrpvfulfvftrjurrlavujnfrtstlrtubnfffvuvrmuur6uvteqvrrruvltnqlvnntdfrmdtvurnrnvdfur7vdfbtfrvtdtbbarfdfrrdetbvbt6vbmvvddrtrlbvvqjprtnruvvrvvnprbj5rfuvndbvavdfvafjbrbsvnrmffvvblrnrbndduvurtffkqtjqfejnuqrfurvfmuuqvbtftmertfevdutefvbtmbeunlnqvrquurpemrmm1b3h3b4zzz84p4i4d3zt3q3j4zc3v4g4b4l3l3zzp3j4x3e4d4j4n3zzzh3a3a3zzzh4n3j4d4e3x4j3zzp3l3l4b3g4v3zc3j4q4zt3d4i4p3zzz83b3h3b2

Something like:

image

### PR DESCRIPTION
**Pull request by despian**
Fixes #299 

Added lines to make it easier to solve large Nuri-Maze puzzles.

I didn't add lines to the auto input mode as I didn't want to break the normal functionality that users may be accustomed to. Seems good enough to me just to be able to select it if needed.

I also added the "Check line connection" mode and the "Color each line" feature, as these are also useful for large puzzles.

### CODE REVIEW

**Comment by x-sheep** [comment]
Saving a puzzle currently doesn't persist the lines.

You can easily test savefiles by pressing Duplicate Board.

**Comment by despian** [comment]
should be good now.

**Comment by despian** [comment]
Does this need a review before being merged?

Let me know if I need to do anything else. Better for me to do it soon before I forget how the app works 😅

**Comment by x-sheep** [comment]
Thanks! I made an additional change where Lines can be erased when clearing all aux. marks, and made the branch up-to-date before merging.

This will be available on puzz.link with the next update.

**Pull request merged**
