### PR TITLE
Add Aquarium type

### PR DESCRIPTION
**Pull request by x-sheep**
I believe the origin for this puzzle type is [Inaba Naoki](http://inabapuzzle.com)'s website in 2004, and is available on PuzzlePicnic as "Water Fun". I don't know if it was included in any Nikoli books. Since the type has recently reappeared on Puzzle Square, I've decided to add an implementation.

Rules:
The grid represents an aquarium viewed from the side, which must be partially filled with water.
- The numbers around the grid indicate the number of shaded cells in that row/column.
- All shaded cells must have a border or another shaded cell below it.
- A single body of water must have the same surface level everywhere (including in U-shaped areas).

This implementation reuses code from the Box puzzle type, and it might be a good idea to move some functions to the shared library.

### CODE REVIEW

**Comment by robx** [comment]
There's one important rule variation around for this type, which is whether disconnected bodies of water within the same region should have the same surface level. I know Puzzle Picnic doesn't require this, while croco-puzzle did. Do the puzsq puzzles and Naoki use the same ruleset as Puzzle Picnic?

**Comment by robx** [comment]
Hmm I just had a look, the first one I found requires same surface levels: http://puzsq.sakura.ne.jp/main/puzzle_play.php?pid=3464

**Comment by x-sheep** [comment]
It's hard to tell with a machine translation, but the description for that specific puzzle seems to mention that it deviates from the rules listed at the top.

Naoki's puzzles don't have U-shaped regions (either up or down).

**Comment by x-sheep** [comment]
The [other puzzle](http://puzsq.sakura.ne.jp/main/puzzle_play.php?pid=3307) on Puzzle Square where this rule could apply also requires the same level with disconnected bodies of water. But this one is listed as a variant, and has additional rules regarding gravity in each region.

**Comment by x-sheep** [comment]
I've now added a checkbox that decides which variation to use, in the style of the `passallcell` option in Arukone.

It's not stable yet, as both of these checkboxes don't always display the actual state after loading a game. This is probably a pre-existing bug.

**Comment by x-sheep** [comment]
I've now fixed it for both this puzzle and Arukone.

**Comment by robx** [comment]
Merged, thanks! https://puzz.link/p?aquarium/7/7/49efvjkh0flqk1atfg/g45442h43452g

**Pull request closed without merging**
