### PR TITLE
Add Tapa-Like Loop

### PR DESCRIPTION
**Pull request by montelucci**
wip

to do:
- [x] editor: enable input numbers by panel
- [x] player: allow placing Xs in cells?
- [x] fix clue input board operations
- [ ] ~move tapa clue drawing to common~
- [x] example
- [x] background
- [x] add to list.html

### CODE REVIEW

**Comment by robx** [comment]
Haven't had an in-depth look yet, but this looks good at first sight. Would be a good type to have, too!

You remarked above that you initially wanted to reuse the tapa clue drawing. Was there a reason to move away from that? Some difference between the two?

It seems likely that there's more code that could/should be shared with tapa. Specifically:

- the new operation
- the key qnum input
- the qnum encoding and decoding

(Happy to help if it's not obvious how to achieve that. Or maybe there's good reasons not to do that.)

**Comment by montelucci** [comment]
I was not comfortable moving stuff to common. The one small difference I introduced is the order the 3- and 4-digit clues are drawn in:
tapaclues
top is tapa, bottom is tapaloop (bottom is how tapa clues are drawn in toketa, [gmpuzzles](https://www.gmpuzzles.com/blog/2014/06/tapa-like-loop-prasanna-seshadri-5/), the puzzle GP, ...).

qnum input and encoding/decoding are different because tapaloop allows bigger clues.

The operation is exactly the same as tapa and can be shared.

One thing I forgot to mention is mouse input. As it is right now, the only way to input numbers on mouse/mobile is using the panel. In tapa, you can click to cycle through all possible clues, but there are 74 of them. They are way more in tapaloop, so that seemed pretty ridiculous to me to implement. I couldn't think of another way

**Comment by robx** [comment]
I think the mouse input is fine. As long as it works, edit mode is not that important.

It's definitely fine (encouraged, even) to move things to the common files.

Regarding the layout, I'm a bit confused, neither approach seems to consistently lay the numbers out increasingly clockwise or anticlockwise? (Haven't checked the code yet.) My first thought is I'd prefer both to use the same code, and the preferably stick with what we have and works for tapa since it's never bothered me, but if there's an obvious improvement to the current tapa layout then changing that would be fine, too.

**Comment by montelucci** [comment]
The second layout is "read line by line"

I moved the original tapa approach to common.
Personally I don't like how e.g. the (1,1,1,3) clue looks in tapaloop

Though to be fair this was never apparent in tapa, since the only valid 4-digit clue there is (1,1,1,1)

**Comment by robx** [comment]
How about

1. changing the orientation of the triple tapa clue to be clockwise, as well (so 1 1 2 would have the 2 at the bottom as opposed to now)
2. changing the quadruple tapa clue to start at the left (wouldn't change any tapa clues, but would move the 3 to the bottom for tapa-like 1 1 1 3)

**Comment by montelucci** [comment]
Funny, I find reading order the most natural. Anyway I made the changes you suggested and they're fine with me

**Comment by montelucci** [comment]
re: moving the operation, not sure where the `sameArray` function should go? (`tapa.js` and `tapaloop.js`, lines 5–15)

**Comment by robx** [comment]
> re: moving the operation, not sure where the `sameArray` function should go? (`tapa.js` and `tapaloop.js`, lines 5–15)

I think it'd probably fit okay in `src/pzpr/util.js` (then called as `pzpr.util.sameArray`). I *hope* we'll be able to share things like that more nicely once the module situation is worked out.

**Comment by robx** [comment]
Sorry this got stalled. Would you be ok with this to be merged if someone finishes it in the future?

**Pull request closed without merging**
