### PR TITLE
Add Norinuri

### PR DESCRIPTION
**Pull request by bay-puz**
I've implemented new genre Norinuri（海苔ぬり）, which first appeared in Puzzle Communication Nikoli vol. 66.

see [Puzzle Square JP](https://puzsq.logicpuzzle.app/?kind=371) or [Janko.at](https://www.janko.at/Raetsel/Norinuri/index.htm)

### CODE REVIEW

**Comment by x-sheep** [comment]
Thanks for the Pull Request! This looks fine to me, but it does currently have a failing unit test.

**Comment by bay-puz** [comment]
Sorry, I made a typo in test.
fix: https://github.com/robx/pzprjs/pull/400/commits/04c551fb173ba7c863f1f8c4f9491647d6763363

**Review by x-sheep — APPROVED** [review]
This looks ready to me 👍 

I don't want to release too many genres at the same time, so I'll merge this at a later date. I'll take care of any merge conflicts.

**Comment by x-sheep** [comment]
I'm planning to release Norinuri this Monday.

**Comment by x-sheep** [comment]
Norinuri is available now.

**Pull request merged**
